name: Reviewdog CI

on: [pull_request]

jobs:
  reviewdog:
    name: Run Reviewdog
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Reviewdog
        run: |
          curl -sfL https://raw.githubusercontent.com/reviewdog/reviewdog/master/install.sh | sh -s -- -b /usr/local/bin

      - name: Run Linter and Reviewdog
        run: |
          echo "Run your linter here and pipe the output to Reviewdog"
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
